repos:
  - repo: local
    hooks:
      - id: check
        name: Check code
        entry: just check
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]
      - id: validate-specs
        name: Validate specs
        entry: go run . validate
        language: system
        types: [markdown]
        pass_filenames: false
        stages: [pre-commit]
