repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/specture-system/specture
    rev: v0.0.0
    hooks:
      - id: validate-specs
  - repo: local
    hooks:
      - id: check
        name: Check code
        entry: just check
        language: system
        types: [go]
        pass_filenames: false
        stages: [pre-commit]
